KerimProje.ToDo.WebUI/Areas/Admin/Controllers/UrgencyController.cs
using KerimProje.ToDo.Business.Interfaces;
using KerimProje.ToDo.Entities.Concrete;
using KerimProje.ToDo.WebUI.Areas.Admin.Models;
using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.Mvc;
using System.Collections.Generic;

namespace KerimProje.ToDo.WebUI.Areas.Admin.Controllers
{
    [Authorize(Roles = "Admin")]
    [Area("Admin")]
    public class UrgencyController : Controller
    {
        private readonly IUrgencyService _urgencyService;
        public UrgencyController(IUrgencyService urgencyService)
        {
            _urgencyService = urgencyService;
        }

        public IActionResult Index()
        {
            TempData["Active"] = "urgency";

            List<Urgency> urgencys = _urgencyService.GetAll();
            List<UrgencyListViewModel> model = new List<UrgencyListViewModel>();
            foreach (var item in urgencys)
            {
                UrgencyListViewModel urgencyListViewModel = new UrgencyListViewModel();
                urgencyListViewModel.Id = item.Id;
                urgencyListViewModel.Definition = item.Definition;

                model.Add(urgencyListViewModel);
            }
            return View(model);
        }


        public IActionResult AddUrgency()
        {
            TempData["Active"] = "urgency";
            return View(new UrgencyAddViewModel());
        }

        [HttpPost]
        public IActionResult AddUrgency(UrgencyAddViewModel model)
        {
            if (ModelState.IsValid)
            {
                _urgencyService.Save(new Urgency()
                {
                    Definition = model.Definition
                });
                return RedirectToAction("Index");
            }
            return View();
        }
        public IActionResult UpdateUrgency(int id)
        {
            TempData["Active"] = "urgency";
            var urgency = _urgencyService.GetById(id);
            UrgencyUpdateViewModel model = new UrgencyUpdateViewModel
            {
                Id = urgency.Id,
                Definition = urgency.Definition
            };
            return View(model);
        }

        [HttpPost]
        public IActionResult UpdateUrgency(UrgencyUpdateViewModel model)
        {
            if (ModelState.IsValid)
            {
                _urgencyService.Update(new Urgency
                {
                    Id = model.Id,
                    Definition = model.Definition
                });
                return RedirectToAction("Index");
            }
            return View(model);
        }

    }
}

KerimProje.ToDo.WebUI/Areas/Admin/Views/Urgency/AddUrgency.cshtml
@model UrgencyAddViewModel

@{
    ViewData["Title"] = "AddUrgency";
    Layout = "~/Areas/Admin/Views/Shared/_AdminLayout.cshtml";
}

<form class="w-75 mx-auto p-3" method="post">
    <div class="form-group">
        <label asp-for="Definition"></label>
        <span asp-validation-for="Definition" class="text-danger"></span>
        <input type="text" asp-for="Definition" class="form-control" />
    </div>
    <button type="submit" class="btn btn-info btn-sm">Save</button>
</form>

@section JavaScriptCode{
    <script src="~/lib/jqueryValidate/jquery.validate.min.js"></script>
    <script src="~/lib/jqueryUnob/jquery.validate.unobtrusive.min.js"></script>
}

KerimProje.ToDo.WebUI/Areas/Admin/Views/Urgency/Index.cshtml
@model List<UrgencyListViewModel>
@{
    ViewData["Title"] = "Index";
    Layout = "~/Areas/Admin/Views/Shared/_AdminLayout.cshtml";
}



@if (Model.Count != 0)
{
    <a asp-action="AddUrgency" asp-controller="Urgency" class="btn btn-sm btn-info my-2">Add Urgency</a>
    <table class="table table-sm table-hover">
        <thead>
            <tr>
                <th>Definition</th>
                <th>Operation</th>
            </tr>
        </thead>
        <tbody>
            @foreach (var item in Model)
            {
                <tr>
                    <td>@item.Definition</td>
                    <td><a asp-action="UpdateUrgency" asp-controller="Urgency" asp-route-id="@item.Id" class="btn btn-warning btn-sm">Update</a></td>
                </tr>
            }
        </tbody>
    </table>
}
else
{
    <div class="text-center mt-4">
        <p class="lead">No urgency registered in the system.</p>
        <a asp-action="AddUrgency" asp-controller="Urgency" class="btn btn-sm btn-info">Add Urgency</a>
    </div>
}

KerimProje.ToDo.WebUI/Areas/Admin/Views/Urgency/UpdateUrgency.cshtml
@model UrgencyUpdateViewModel
@{
    ViewData["Title"] = "UpdateUrgency";
    Layout = "~/Areas/Admin/Views/Shared/_AdminLayout.cshtml";
}

<form asp-action="UpdateUrgency" class="w-75 mx-auto p-3" method="post">
    <input type="hidden" asp-for="Id" />
    <div class="form-group">
        <label asp-for="Definition"></label>
        <span asp-validation-for="Definition" class="text-danger"></span>
        <input type="text" asp-for="Definition" class="form-control" />
    </div>
    <button type="submit" class="btn btn-info btn-sm">Update</button>
</form>

@section JavaScriptCode{
    <script src="~/lib/jqueryValidate/jquery.validate.min.js"></script>
    <script src="~/lib/jqueryUnob/jquery.validate.unobtrusive.min.js"></script>
}